# Generated by Django 3.0.2 on 2020-03-20 09:02

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sup_dept', models.CharField(max_length=75)),
                ('sample_from_outside', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('origin_of_sample', models.CharField(max_length=75)),
                ('req_discussed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='faculties', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
                'default_related_name': 'faculties',
            },
            bases=('booking_portal.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FESEM',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(choices=[('Metal', 'Metal'), ('Film', 'Film'), ('Crystal', 'Crystal'), ('Powder', 'Powder'), ('Biological', 'Biological'), ('Ceramic', 'Ceramic'), ('Tissue', 'Tissue'), ('Others', 'Others')], max_length=15)),
                ('analysis_nature', models.CharField(max_length=75)),
                ('sputter_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('other_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='FTIR',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('composition', models.CharField(max_length=75)),
                ('state', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid')], max_length=10)),
                ('solvent', models.CharField(max_length=75)),
                ('other_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='LabAssistant',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='labassistants', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lab assistant',
                'default_related_name': 'labassistants',
            },
            bases=('booking_portal.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LCMS',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('composition', models.CharField(max_length=75)),
                ('phase', models.CharField(max_length=75)),
                ('no_of_lc_peaks', models.IntegerField()),
                ('solvent_solubility', models.CharField(max_length=75)),
                ('exact_mass', models.CharField(max_length=75)),
                ('mass_adducts', models.CharField(max_length=75)),
                ('analysis_mode', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10)),
                ('other_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='students', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'student',
                'default_related_name': 'students',
            },
            bases=('booking_portal.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TCSPC',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(choices=[('Metal', 'Metal'), ('Film', 'Film'), ('Crystal', 'Crystal'), ('Powder', 'Powder'), ('Biological', 'Biological'), ('Ceramic', 'Ceramic'), ('Tissue', 'Tissue'), ('Others', 'Others')], max_length=15)),
                ('chemical_composition', models.CharField(max_length=75)),
                ('other_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('S1', 'Empty'), ('S2', 'In Process'), ('S3', 'Filled'), ('S4', 'Passed')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R1', 'Waiting for faculty approval.'), ('R2', 'Waiting for lab assistant approval.'), ('R3', 'Approved'), ('R4', 'Rejected'), ('R5', 'Cancelled')], max_length=50)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Instrument')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_portal.Slot')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Faculty')),
                ('lab_assistant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.LabAssistant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Student')),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.EmailField(max_length=254, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Request')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sup_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_portal.Faculty'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_portal.Student'),
        ),
    ]
