# Generated by Django 3.0.2 on 2020-01-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Faculty'),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Student'),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('S1', 'Empty'), ('S2', 'In Process'), ('S3', 'Filled'), ('S4', 'Passed')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField(null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S1', 'Waiting for faculty approval.'), ('S2', 'Waiting for lab assistant approval.'), ('S3', 'Approved'), ('S4', 'Rejected'), ('S5', 'Cancelled')], max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Faculty')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Instrument')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_portal.Slot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Student')),
            ],
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Instrument'),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.Request'),
        ),
    ]
