# Generated by Django 3.0.2 on 2020-03-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AAS',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('elements', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='BET',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('pretreatment_conditions', models.CharField(max_length=75)),
                ('precautions', models.CharField(max_length=75)),
                ('adsorption', models.CharField(max_length=75)),
                ('surface_area', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='Rheometer',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('ingredient_details', models.CharField(max_length=75)),
                ('physical_characteristics', models.CharField(max_length=75)),
                ('chemical_nature', models.CharField(max_length=75)),
                ('origin', models.CharField(choices=[('Natural', 'Natural'), ('Synthetic', 'Synthetic')], max_length=10)),
                ('analysis_required', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='TGA',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('chemical_composition', models.CharField(max_length=75)),
                ('sample_amount', models.CharField(max_length=75)),
                ('heating_program', models.CharField(choices=[('Dynamic', 'Dynamic'), ('Isothermal', 'Isothermal')], max_length=15)),
                ('temperature', models.CharField(max_length=75)),
                ('atmosphere', models.CharField(choices=[('N2', 'N2'), ('Ar', 'Ar'), ('Air', 'Air')], max_length=5)),
                ('heating_rate', models.CharField(max_length=75)),
                ('sample_solubility', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
    ]
