# Generated by Django 3.0.2 on 2020-01-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0002_auto_20200127_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
