# Generated by Django 3.0.2 on 2020-03-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0003_cdspectrophotometer_dsc_gc_lscm'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDXRF',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(choices=[('Powder', 'Powder'), ('Metal', 'Metal'), ('Film', 'Film'), ('Biological', 'Biological'), ('Concrete', 'Concrete')], max_length=15)),
                ('elements_present', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='HPLC',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_information', models.CharField(max_length=75)),
                ('mobile_phase', models.CharField(max_length=75)),
                ('column_for_lc', models.CharField(max_length=75)),
                ('detection_wavelength', models.CharField(max_length=75)),
                ('other_information', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='NMR',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid')], max_length=10)),
                ('quantity', models.CharField(max_length=75)),
                ('solvent', models.CharField(max_length=75)),
                ('analysis', models.CharField(max_length=75)),
                ('experiment', models.CharField(max_length=75)),
                ('spectral_range', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='PXRD',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('chemical_composition', models.CharField(max_length=75)),
                ('sample_description', models.CharField(choices=[('Film', 'Film'), ('Powder', 'Powder'), ('Pellet', 'Pellet')], max_length=10)),
                ('range', models.CharField(max_length=75)),
                ('scanning_rate', models.CharField(max_length=75)),
                ('any_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='SCXRD',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('chemical_composition', models.CharField(max_length=75)),
                ('scanning_rate', models.CharField(max_length=75)),
                ('source', models.CharField(choices=[('Cu', 'Cu'), ('Mo', 'Mo')], max_length=5)),
                ('any_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='UVSpectrophotometer',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_composition', models.CharField(max_length=75)),
                ('molecular_weight', models.CharField(max_length=75)),
                ('analysis_mode', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid'), ('Thin Film', 'Thin Film')], max_length=10)),
                ('wavelength', models.CharField(max_length=75)),
                ('ordinate_mode', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
        migrations.CreateModel(
            name='XPS',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_name', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(max_length=75)),
                ('chemical_composition', models.CharField(max_length=75)),
                ('sample_property', models.CharField(choices=[('Conducting', 'Conducting'), ('Semi Conducting', 'Semi Conducting'), ('Insulating', 'Insulating')], max_length=20)),
                ('analysed_elements', models.CharField(max_length=75)),
                ('scan_details', models.CharField(max_length=75)),
            ],
            bases=('booking_portal.userdetails',),
        ),
    ]
