# Generated by Django 3.0.2 on 2020-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0004_edxrf_hplc_nmr_pxrd_scxrd_uvspectrophotometer_xps'),
    ]

    operations = [
        migrations.AddField(
            model_name='aas',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdspectrophotometer',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsc',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edxrf',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gc',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nmr',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rheometer',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tga',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uvspectrophotometer',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xps',
            name='other_remarks',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
