# Generated by Django 3.0.2 on 2020-04-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booking_portal', '0005_auto_20200322_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aas',
            options={'verbose_name': 'AAS', 'verbose_name_plural': 'AAS'},
        ),
        migrations.AlterModelOptions(
            name='bet',
            options={'verbose_name': 'BET', 'verbose_name_plural': 'BET'},
        ),
        migrations.AlterModelOptions(
            name='cdspectrophotometer',
            options={'verbose_name': 'CDSpectrophotometer', 'verbose_name_plural': 'CDSpectrophotometer'},
        ),
        migrations.AlterModelOptions(
            name='dsc',
            options={'verbose_name': 'DSC', 'verbose_name_plural': 'DSC'},
        ),
        migrations.AlterModelOptions(
            name='edxrf',
            options={'verbose_name': 'EDXRF', 'verbose_name_plural': 'EDXRF'},
        ),
        migrations.AlterModelOptions(
            name='fesem',
            options={'verbose_name': 'FESEM', 'verbose_name_plural': 'FESEM'},
        ),
        migrations.AlterModelOptions(
            name='ftir',
            options={'verbose_name': 'FTIR', 'verbose_name_plural': 'FTIR'},
        ),
        migrations.AlterModelOptions(
            name='gc',
            options={'verbose_name': 'GC', 'verbose_name_plural': 'GC'},
        ),
        migrations.AlterModelOptions(
            name='hplc',
            options={'verbose_name': 'HPLC', 'verbose_name_plural': 'HPLC'},
        ),
        migrations.AlterModelOptions(
            name='lcms',
            options={'verbose_name': 'LCMS', 'verbose_name_plural': 'LCMS'},
        ),
        migrations.AlterModelOptions(
            name='lscm',
            options={'verbose_name': 'LSCM', 'verbose_name_plural': 'LSCM'},
        ),
        migrations.AlterModelOptions(
            name='nmr',
            options={'verbose_name': 'NMR', 'verbose_name_plural': 'NMR'},
        ),
        migrations.AlterModelOptions(
            name='pxrd',
            options={'verbose_name': 'PXRD', 'verbose_name_plural': 'PXRD'},
        ),
        migrations.AlterModelOptions(
            name='rheometer',
            options={'verbose_name': 'Rheometer', 'verbose_name_plural': 'Rheometer'},
        ),
        migrations.AlterModelOptions(
            name='scxrd',
            options={'verbose_name': 'SCXRD', 'verbose_name_plural': 'SCXRD'},
        ),
        migrations.AlterModelOptions(
            name='tcspc',
            options={'verbose_name': 'TCSPC', 'verbose_name_plural': 'TCSPC'},
        ),
        migrations.AlterModelOptions(
            name='tga',
            options={'verbose_name': 'TGA', 'verbose_name_plural': 'TGA'},
        ),
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Detail', 'verbose_name_plural': 'User Details'},
        ),
        migrations.AlterModelOptions(
            name='uvspectrophotometer',
            options={'verbose_name': 'UVSpectrophotometer', 'verbose_name_plural': 'UVSpectrophotometer'},
        ),
        migrations.AlterModelOptions(
            name='xps',
            options={'verbose_name': 'XPS', 'verbose_name_plural': 'XPS'},
        ),
        migrations.AddField(
            model_name='request',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='request',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='lab_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.LabAssistant'),
        ),
    ]
