# Generated by Django 3.0.2 on 2020-03-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0005_auto_20200308_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lab_assistant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking_portal.LabAssistant'),
        ),
    ]
