# Generated by Django 3.0.2 on 2020-03-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0006_request_lab_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('R1', 'Waiting for faculty approval.'), ('R2', 'Waiting for lab assistant approval.'), ('R3', 'Approved'), ('R4', 'Rejected'), ('R5', 'Cancelled')], max_length=50),
        ),
    ]
