# Generated by Django 3.0.2 on 2020-03-11 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0007_auto_20200311_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=75)),
                ('date', models.DateField(default=datetime.date.today)),
                ('sup_name', models.CharField(max_length=75)),
                ('sup_dept', models.CharField(max_length=75)),
                ('sample_from_outside', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('origin_of_sample', models.CharField(max_length=75)),
                ('req_discussed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
    ]
