# Generated by Django 3.0.2 on 2020-03-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0009_fesem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCSPC',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('sample_nature', models.CharField(choices=[('Metal', 'Metal'), ('Film', 'Film'), ('Crystal', 'Crystal'), ('Powder', 'Powder'), ('Biological', 'Biological'), ('Ceramic', 'Ceramic'), ('Tissue', 'Tissue'), ('Others', 'Others')], max_length=15)),
                ('chemical_composition', models.CharField(max_length=75)),
                ('other_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
    ]
