# Generated by Django 3.0.2 on 2021-01-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0009_hplc_fd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name']},
        ),
    ]
