# Generated by Django 3.0.2 on 2020-03-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0010_tcspc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTIR',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('composition', models.CharField(max_length=75)),
                ('state', models.CharField(choices=[('Solid', 'Solid'), ('Liquid', 'Liquid')], max_length=10)),
                ('solvent', models.CharField(max_length=75)),
                ('other_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
    ]
