# Generated by Django 3.0.2 on 2020-03-11 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0011_ftir'),
    ]

    operations = [
        migrations.CreateModel(
            name='LCMS',
            fields=[
                ('userdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='booking_portal.UserDetails')),
                ('sample_code', models.CharField(max_length=75)),
                ('composition', models.CharField(max_length=75)),
                ('phase', models.CharField(max_length=75)),
                ('no_of_lc_peaks', models.IntegerField()),
                ('solvent_solubility', models.CharField(max_length=75)),
                ('exact_mass', models.CharField(max_length=75)),
                ('mass_adducts', models.CharField(max_length=75)),
                ('analysis_mode', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=10)),
                ('other_remarks', models.CharField(max_length=200)),
            ],
            bases=('booking_portal.userdetails',),
        ),
    ]
