# Generated by Django 3.2.5 on 2021-10-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0016_auto_20210929_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utm',
            name='test_speed',
            field=models.DecimalField(decimal_places=2, max_digits=7, help_text='<small>Precision upto 2 decimal places</small>'),
        ),
    ]
