# Generated by Django 3.2.5 on 2021-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_portal', '0017_alter_utm_test_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utm',
            name='test_speed',
            field=models.DecimalField(decimal_places=4, help_text='<small>Precision upto 4 decimal places</small>', max_digits=9),
        ),
    ]
