from .aas import AASForm
from .bet import BETForm
from .cdspectrophotometer import CDSpectrophotometerForm
from .dsc import DSCForm
from .edxrf import EDXRFForm
from .fesem import FESEMForm
from .ftir import FTIRForm
from .gc import GCForm
from .hplc import HPLCForm
from .hplc_fd import HPLC_FDForm
from .lcms import LCMSForm
from .lscm import LSCMForm
from .nmr import NMRForm
from .pxrd import PXRDForm
from .rheometer import RheometerForm
from .scxrd import SCXRDForm
from .tcspc import TCSPCForm
from .tga import TGAForm
from .uvspectrophotometer import UVSpectrophotometerForm
from .xps import XPSForm
