from .form_models import (AAS,
                          BET,
                          CDSpectrophotometer,
                          DSC,
                          EDXRF,
                          FESEM,
                          FTIR,
                          GC,
                          HPLC,
                          LCMS,
                          LSCM,
                          NMR,
                          PXRD,
                          Rheometer,
                          SCXRD,
                          TCSPC,
                          TGA,
                          UVSpectrophotometer,
                          UVSpectrophotometer,
                          XPS)
from .userdetails import UserDetail
from .instrument import Instrument